---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: clair
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-clairctl
data:
  clairctl.yml: |
    clair:
      port: 6060
      healthPort: 6061
      uri: 'http://{{ template "fullname" . }}'
      report:
        path: /reports
        format: html
