---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-clairctl
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    role: clairctl
spec:
  serviceName: {{ template "fullname" . }}-clairctl
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        role: clairctl
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
              {
                "name": "var-www",
                "image": "busybox",
                "command": [
                  "mkdir",
                  "-p",
                  "/var/www/html"
                ],
                "volumeMounts": [
                  {
                    "name": "index-php",
                    "mountPath": "/config"
                  },
                  {
                    "name": "reports",
                    "mountPath": "/var/www/"
                  }
                ]
              },
              {
                "name": "index-php",
                "image": "busybox",
                "command": [
                  "cp",
                  "-u",
                  "/config/index.php",
                  "/var/www/html/index.php"
                ],
                "volumeMounts": [
                  {
                    "name": "index-php",
                    "mountPath": "/config"
                  },
                  {
                    "name": "reports",
                    "mountPath": "/var/www/"
                  }
                ]
              }


        ]'
    spec:
      containers:
      - name: {{ template "fullname" . }}-clairctl
        imagePullPolicy: Always
        image: sudermanjr/clairctl:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /reports
          name: reports
        - mountPath: /root
          name: clairctl-config
      - name: {{ template "fullname" . }}-php
        imagePullPolicy: Always
        image: php:7-apache
        ports:
        - containerPort: 80
          name: php-port
        volumeMounts:
        - mountPath: /var/www
          name: reports
        - mountPath: /usr/local/etc/php/
          name: php-config
      volumes:
      - name: clairctl-config
        configMap:
          name: {{ template "fullname" . }}-clairctl
      - name: php-config
        configMap:
          name: {{ template "fullname" . }}-php
      - name: index-php
        configMap:
          name: {{ template "fullname" . }}-index-php
  volumeClaimTemplates:
  - metadata:
      name: reports
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
