apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-clairctl
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    role: clairctl
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: clairctl-port
  selector:
    app: {{ template "fullname" . }}
    role: clairctl
