apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    role: clair
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.servicePort1 }}
    targetPort: 6060
    protocol: TCP
    name: clair-port0
  - port: {{ .Values.service.servicePort2 }}
    targetPort: 6061
    protocol: TCP
    name: clair-port1
  selector:
    app: {{ template "fullname" . }}
    role: clair
