apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    role: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: pg-port
  selector:
    app: {{ template "fullname" . }}
    role: database
