---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: clair
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-index-php
data:
  index.php: |
    <?php
    echo "<h2>Container Vulnerability Reports</h2>";
    $path = ".";
    $dh = opendir($path);
    $i=1;
    while (($file = readdir($dh)) !== false) {
        if($file != "." && $file != ".." && $file != "index.php" && $file != ".htaccess" && $file != "error_log" && $file != "cgi-bin") {
            echo "<a href='$path/$file'>$file</a><br /><br />";
            $i++;
        }
    }
    closedir($dh);
    ?>
