---
apiVersion: v1
kind: Pod
metadata:
  name: clairctl
  labels:
    purpose: testing
    app: clair
spec:
  containers:
  - name: clairctl
    imagePullPolicy: Always 
    image: sudermanjr/clairctl:latest
    securityContext:
      privileged: true
