# Default values for clair-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/coreos/clair
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  servicePort1: 6060
  servicePort2: 6061
clairctl:
  vhost: clair.yourdomain.com
# resources:
#   limits:
#     cpu: 100m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 256Mi
postgres:
  password: "changeme"
