# Default values for clair-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/coreos/clair
  tag: latest
  pullPolicy: Always
service:
  name: clair
  type: ClusterIP
  servicePort1: 6060
  servicePort2: 6061
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
# resources:
#   limits:
#     cpu: 100m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 256Mi
postgres:
  password: "changeme"